# Generated by Django 4.1 on 2022-10-28 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversalDrill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_param_start', models.PositiveIntegerField(default=1, verbose_name='Start1')),
                ('first_param_end', models.PositiveIntegerField(default=30, verbose_name='End1')),
                ('second_param_start', models.PositiveIntegerField(default=1, verbose_name='Start2')),
                ('second_param_end', models.PositiveIntegerField(default=30, verbose_name='End2')),
                ('operation', models.CharField(choices=[('+', 'Addition'), ('-', 'Subtraction'), ('x', 'Multiplication'), ('÷', 'Division'), ('^', 'Exponent'), ('√a', 'Roots')], default='x', max_length=3)),
                ('name', models.CharField(default='', max_length=50)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Competitive Exam'), (2, 'Student'), (3, 'Neurobics'), (4, 'Just Playing'), (5, 'Consultant')], default=1)),
            ],
            options={
                'verbose_name': 'Universal Drill',
                'verbose_name_plural': 'Universal Drills',
            },
        ),
        migrations.CreateModel(
            name='UserDrill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_param_start', models.PositiveIntegerField(default=1, verbose_name='Start1')),
                ('first_param_end', models.PositiveIntegerField(default=30, verbose_name='End1')),
                ('second_param_start', models.PositiveIntegerField(default=1, verbose_name='Start2')),
                ('second_param_end', models.PositiveIntegerField(default=30, verbose_name='End2')),
                ('operation', models.CharField(choices=[('+', 'Addition'), ('-', 'Subtraction'), ('x', 'Multiplication'), ('÷', 'Division'), ('^', 'Exponent'), ('√a', 'Roots')], default='x', max_length=3)),
                ('name', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Drill',
                'verbose_name_plural': 'User Drills',
            },
        ),
    ]
