# Generated by Django 4.1 on 2022-10-26 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversalDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_param_start', models.PositiveIntegerField(default=1, verbose_name='Start1')),
                ('first_param_end', models.PositiveIntegerField(default=30, verbose_name='End1')),
                ('second_param_start', models.PositiveIntegerField(default=1, verbose_name='Start2')),
                ('second_param_end', models.PositiveIntegerField(default=30, verbose_name='End2')),
                ('operation', models.PositiveSmallIntegerField(choices=[(1, '+'), (2, '-'), (3, 'x'), (4, '÷'), (5, '^'), (6, '√a')], default=3)),
                ('name', models.CharField(default='', max_length=50)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Competitive Exam'), (2, 'Student'), (3, 'Neurobics'), (4, 'Just Playing')], default=1)),
            ],
            options={
                'verbose_name': 'Drill',
                'verbose_name_plural': 'Drills',
            },
        ),
        migrations.CreateModel(
            name='UserDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_param_start', models.PositiveIntegerField(default=1, verbose_name='Start1')),
                ('first_param_end', models.PositiveIntegerField(default=30, verbose_name='End1')),
                ('second_param_start', models.PositiveIntegerField(default=1, verbose_name='Start2')),
                ('second_param_end', models.PositiveIntegerField(default=30, verbose_name='End2')),
                ('operation', models.PositiveSmallIntegerField(choices=[(1, '+'), (2, '-'), (3, 'x'), (4, '÷'), (5, '^'), (6, '√a')], default=3)),
                ('name', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drill',
                'verbose_name_plural': 'Drills',
            },
        ),
    ]
