# Generated by Django 4.1 on 2022-10-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universaldrill',
            options={'verbose_name': 'Universal Drill', 'verbose_name_plural': 'Universal Drills'},
        ),
        migrations.AlterModelOptions(
            name='userdrill',
            options={'verbose_name': 'User Drill', 'verbose_name_plural': 'User Drills'},
        ),
    ]
