# Generated by Django 4.1 on 2022-10-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0002_alter_universaldrill_options_alter_userdrill_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universaldrill',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Competitive Exam'), (2, 'Student'), (3, 'Neurobics'), (4, 'Just Playing'), (5, 'Consultant')], default=1),
        ),
    ]
