# Generated by Django 4.1 on 2022-11-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smduser',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
